extraction:
    cpp:
        prepare:
            packages:
                - pkg-config
                - cmake
                - libcurl4-openssl-dev
                - libxml2-dev
                - ninja-build
                - python3-pip
                - python3-setuptools
        after_prepare:
            - pip3 install meson
        configure:
            command:
                - meson build
        index:
            build_command:
                - cd build && ninja
